skip_branch_with_pr: true

environment:
  matrix:
  - nodejs_version: "6.0"
  APPVEYOR_RDP_PASSWORD: "ungit-rdp"

branches:
  only:
    - master

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - npm cach clean
  - npm install
  - npm install -g grunt-cli

test_script:
  - node --version
  - npm --version
  - grunt
  - npm test

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
